version: "3.8"

services:
  redis:
    image: "redis:alpine"
    ports:
      - 6380:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  association:
    build:
      context: ./association
      target: development
    volumes:
      - ./association:/src
      - /src/node_modules
    command: npm run start:dev
    ports:
      - "8123:8000"
    environment:
      - REDIS_SERVER=redis:6379
      - LOG_SERVICE=log:8000
      - AUTH_SERVICE=authentication:8000
      - USER_SERVICE=user:8000
      - NAME=association-service
    depends_on:
      - redis

  vehicles:
    build:
      context: ./vehicles
      target: development
    volumes:
      - ./vehicles:/src
      - /src/node_modules
    command: npm run start:dev
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: development
      DEBUG: src:*
    
  notification:
    build:
      context: ./notifications
      target: development
    volumes:
      - ./notifications:/src
      - /src/node_modules
    command: npm run start
    ports:
      - "8004:8000"
    environment: 
      NODE_ENV: development
      DEBUG: src:*

  payment:
    build:
      context: ./PricingService
      target: development
    volumes:
      - ./PricingService:/src
      - /src/node_modules
    command: npm run start
    ports:
      - "8006:8000"
    environment: 
      NODE_ENV: development
      DEBUG: src:*

  gestion_taches_agent:
    build:
      context: ./gestion_taches_agent
      target: development
    volumes:
      - ./gestion_taches_agent:/src
      - /src/node_modules
    command: npm run start:dev
    ports:
      - "8001:8000"
    environment:
      NODE_ENV: development
      DEBUG: src:*

  user:
    build:
      context: ./user
      target: development
    volumes:
      - ./user:/src
      - /src/node_modules
    command: npm run start:dev
    ports:
      - "8100:8000"
    environment:
      NODE_ENV: development
      DEBUG: src:*

  tracking:
    build:
      context: ./tracking
      target: development
    volumes:
      - ./tracking:/src
      - /src/node_modules
    command: npm run start:dev
    ports:
      - "8003:8001"
    environment:
      NODE_ENV: development
      DEBUG: src:*

  borne-vehicule:
    build:
      context: ./borne-vehicule
      target: development
    volumes:
      - ./borne-vehicule:/src
      - /src/node_modules
    command: npm run start:dev
    ports:
      - "8200:8000"
    environment:
      NODE_ENV: development
      DEBUG: src:*

  geolocalisation:
    build:
      context: ./geolocalisation
      target: development
    volumes:
      - ./geolocalisation:/src
      - /src/node_modules
    command: npm run start:dev
    ports:
      - "8002:8002"
    environment:
      NODE_ENV: development
      DEBUG: src:*

  authentication:
    build:
      context: ./Authentication
      target: development
    volumes:
      - ./Authentication:/src
      - /src/node_modules
    command: npm run start:dev
    ports:
      - "8005:8000"
    environment:
      NODE_ENV: development
      DEBUG: src:*
  stats:
    build:
      context: ./stats
      target: development
    volumes:
      - ./stats:/src
      - /src/node_modules
    command: npm run start:dev
    ports:
      - "8089:8000"
    environment:
      NODE_ENV: development
      DEBUG: src:*

  state:
    build:
      context: ./details_tech_bylocation
      target: development
    volumes:
      - ./details_tech_bylocation:/src
      - /src/node_modules
    command: npm run start:dev
    ports:
      - "8400:8000"
    environment:
      NODE_ENV: development
      DEBUG: src:*
  location:
    build:
      context: ./position_bylocation
      target: development
    volumes:
      - ./position_bylocation:/src
      - /src/node_modules
    command: npm run start
    ports:
      - "8500:8500"
    environment: 
      NODE_ENV: development
      DEBUG: src:*
      
