version: '3.8'
services:
    userapi:
      build:
          context: ./userapi
          target: development
      volumes:
          - ./userapi:/src
          - /src/node_modules
      command: npm run start:dev
      ports:
          - "8000:8000"
      environment: 
          NODE_ENV: development
          DEBUG: src:*
    